const OPERATOR_REGISTRATION_RESULT_SIZES = {
    VERSION: 1,
    REPORT_TYPE: 1,
    OPERATOR: 32,
    CHAIN_TYPES_LENGTH: 4,
    OPERATOR_ADDRESSES_LENGTH: 4,
};

const OPERATOR_REGISTRATION_RESULT_OFFSETS = {
    VERSION: 0,
    REPORT_TYPE: 1, // After VERSION
    OPERATOR: 2, // After REPORT_TYPE
    CHAIN_TYPES_LENGTH: 34, // After OPERATOR
    CHAIN_TYPES: 38, // After CHAIN_TYPES_LENGTH
};

export { OPERATOR_REGISTRATION_RESULT_SIZES, OPERATOR_REGISTRATION_RESULT_OFFSETS };
