const OPERATOR_REGISTRATION_RESULT_SIZES = {
    VERSION: 1,
    REPORT_TYPE: 1,
    OPERATORS_COUNT: 2,
    OPERATOR: 32,
    CHAIN_TYPES_LENGTH: 4,
    OPERATOR_ADDRESSES_LENGTH: 4,
};

export { OPERATOR_REGISTRATION_RESULT_SIZES };
