# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   cre-cli:
#     don-family: "zone-a"                          # Required: Workflow DON Family
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-mainnet                # Required: Chain RPC endpoints
#       url: "https://mainnet.infura.io/v3/KEY"

# ==========================================================================
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://gateway.tenderly.co/public/sepolia

# ==========================================================================
staging:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://gateway.tenderly.co/public/sepolia
    - chain-name: ethereum-mainnet
      url: https://mainnet.gateway.tenderly.co