# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   cre-cli:
#     don-family: "zone-a"                          # Required: Workflow DON Family
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-mainnet                # Required: Chain RPC endpoints
#       url: "https://mainnet.infura.io/v3/KEY"

# ==========================================================================
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-public.nodies.app

# ==========================================================================
stage-testnet:
  account:
    workflow-owner-address: "0x1D218D445b69c7eFa20be0DC120B8d001440f15C"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-public.nodies.app
    - chain-name: ethereum-mainnet
      url: https://ethereum-public.nodies.app

production-testnet:
  account:
    workflow-owner-address: "0x1D218D445b69c7eFa20be0DC120B8d001440f15C"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-public.nodies.app
    - chain-name: ethereum-mainnet
      url: https://ethereum-public.nodies.app

production-mainnet:
  account:
    workflow-owner-address: "0x1D218D445b69c7eFa20be0DC120B8d001440f15C"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-public.nodies.app
    - chain-name: ethereum-mainnet
      url: https://ethereum-public.nodies.app
