const CLF_SECRETS_TESTNET_EXPIRATION = 4320;
const CLF_SECRETS_ETHEREUM_EXPIRATION = 129600;
const CLF_DON_HOSTED_SECRETS_SLOT = "3";

//CLF Secrets TTL
const CLF_MAINNET_TTL = 7776000;
const CLF_TESTNET_TTL = 129600;

export {
	CLF_SECRETS_TESTNET_EXPIRATION,
	CLF_SECRETS_ETHEREUM_EXPIRATION,
	CLF_DON_HOSTED_SECRETS_SLOT,
	CLF_MAINNET_TTL,
	CLF_TESTNET_TTL,
};
