export const REPORT_BYTE_SIZES = {
	// Message report response byte sizes
	INTERNAL_MESSAGE_CONFIG: 32,
	MESSAGE_ID: 32,
	MESSAGE_HASH_SUM: 32,
	ALLOWED_OPERATORS_LENGTH: 2,
	ALLOWED_OPERATORS: 32,
} as const;
