#!/usr/bin/env sh
set -euo pipefail

# Branch name validation
./$(dirname "$0")/validateBranchName.sh

# Pre-commit checks
yarn hardhat compile
yarn format:ts
yarn format:sol
#yarn lint:ts
#yarn lint:sol
make test

echo "✅ Pre-commit checks passed successfully."
exit 0
