export enum ErrorCode {
	UNKNOWN_ERROR = "UNKNOWN_ERROR",
	INVALID_BYTES_ARGS_LENGTH = "INVALID_BYTES_ARGS_LENGTH",

	// Configuration Errors
	CONFIG_INVALID_VERSION = "CONFIG_INVALID_VERSION",
	CONFIG_INVALID_RELAYER_CONFIG = "CONFIG_INVALID_RELAYER_CONFIG",
	CONFIG_INVALID_MIN_SRC_CONFIRMATIONS = "CONFIG_INVALID_MIN_SRC_CONFIRMATIONS",
	CONFIG_INVALID_MIN_DST_CONFIRMATIONS = "CONFIG_INVALID_MIN_DST_CONFIRMATIONS",
	CONFIG_INVALID_SRC_CHAIN_SELECTOR = "CONFIG_INVALID_SRC_CHAIN_SELECTOR",
	CONFIG_INVALID_DST_CHAIN_SELECTOR = "CONFIG_INVALID_DST_CHAIN_SELECTOR",
	INVALID_MESSAGE_CONFIG = "INVALID_MESSAGE_CONFIG",

	// Chain and RPC Errors
	NO_CHAIN_DATA = "NO_CHAIN_DATA",
	NO_RPC_DATA = "NO_RPC_DATA",
	NO_RPC_PROVIDERS = "NO_RPC_PROVIDERS",
	INVALID_SOURCE_CHAIN = "INVALID_SOURCE_CHAIN",
	INVALID_DESTINATION_CHAIN = "INVALID_DESTINATION_CHAIN",
	INVALID_CHAIN = "INVALID_CHAIN",
	INVALID_RPC = "INVALID_RPC",

	// Event and Message Errors
	EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
	INVALID_MESSAGE_ID = "INVALID_MESSAGE_ID",
	INVALID_DATA = "INVALID_DATA",
	INVALID_HASH_SUM = "INVALID_HASH_SUM",
	INVALID_CHAIN_DATA = "INVALID_CHAIN_DATA",

	INVALID_VALIDATOR = "INVALID_VALIDATOR",

	FAILED_TO_FETCH_CHAINS_CONFIG = "FAILED_TO_FETCH_CHAINS_CONFIG",
}
